### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by yeongjet** [casesandberg/react-bounds#11]
https://github.com/jettangs/test-react-bounds

there is an error in Chrome:
`Component.js:3 Uncaught TypeError: Super expression must either be null or a function, not undefined(…)`

**Comment by casesandberg** [comment]
ReactCSS actually has a different syntax 1.X.X and that is why you are getting that error. See more details about the new API here: http://reactcss.com/

**Comment by yeongjet** [comment]
now I rewrite it, but the styles does't work, the background have no any change.
