### ISSUE TITLE
The components doesn't get rendered .

### ISSUE THREAD

**Issue by TRomesh** [casesandberg/react-bounds#16]
I've tried to use this component but the calendar like component doesn't seem to be rendering.
```

import React,{Component} from 'react';
import bounds from 'react-bounds';


class SomeComponent extends Component{
  render(){
    return <div>Some Component</div>
  }
};

export default bounds.wrap(SomeComponent);
```

There are no errors in the consoles. and it only shows the texts ive typed insides the devs

**Comment by casesandberg** [comment]
Hey @TRomesh! Are you trying to use the calendar component itself? This library is just for doing media-style queries, the calendar component was created just for the docs.

**Comment by TRomesh** [comment]
@casesandberg  oops my bad, i didn't went through the readme stuff.
